[project]
name = "test-eel"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "eel>=0.18.2",
    "ezodf>=0.3.2",
    "flask>=3.1.3",
    "lxml>=6.1.1",
    "pandas>=3.0.2",
    "pyinstaller>=6.19.0",
    "python-calamine>=0.6.2",
    "typst>=0.14.8",
]
